---
include:
  # ---- SofleW ----
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display_091_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_dongle